"""initial migration

Revision ID: c1e186e4d709
Revises:
Create Date: 2026-07-14 14:48:33.596601

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1e186e4d709"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("NOTE_PARSE", "WRITING_FEEDBACK", "QUIZ_FEEDBACK", name="approvalsourcetype"),
            nullable=False,
        ),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("item_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("extracted_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("explanation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("example_sentence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_context", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("possible_duplicate_of", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "EDITED_APPROVED", "REJECTED", name="approvalstatus"),
            nullable=False,
        ),
        sa.Column("reviewed_payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["possible_duplicate_of"],
            ["learning_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_approval_queue_item_type"), "approval_queue", ["item_type"], unique=False
    )
    op.create_index(
        op.f("ix_approval_queue_possible_duplicate_of"),
        "approval_queue",
        ["possible_duplicate_of"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_queue_source_id"), "approval_queue", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_approval_queue_source_type"), "approval_queue", ["source_type"], unique=False
    )
    op.create_index(op.f("ix_approval_queue_status"), "approval_queue", ["status"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "PARSE_FAILED",
                "BACKUP_TAKEN",
                "BACKUP_FAILED",
                "CONFIG_CHANGE",
                "APPROVAL_ACTION",
                name="auditeventtype",
            ),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("event_metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_event_type"), "audit_log", ["event_type"], unique=False)
    op.create_index(op.f("ix_audit_log_timestamp"), "audit_log", ["timestamp"], unique=False)
    op.create_table(
        "config",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "learning_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "item_type",
            sa.Enum(
                "COLLOCATION",
                "IDIOM",
                "PHRASAL_VERB",
                "GRAMMAR_NOTE",
                "PERSONAL_EXAMPLE",
                name="itemtype",
            ),
            nullable=False,
        ),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("definition", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("example_sentence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_note_id", sa.Integer(), nullable=True),
        sa.Column("source_approval_id", sa.Integer(), nullable=False),
        sa.Column("mastery_score", sa.Float(), nullable=False),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("incorrect_count", sa.Integer(), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("next_review_due", sa.DateTime(), nullable=True),
        sa.Column("ease_factor", sa.Float(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("suspended", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_approval_id"],
            ["approval_queue.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_note_id"],
            ["note.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_item_created_at"), "learning_item", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_learning_item_item_type"), "learning_item", ["item_type"], unique=False
    )
    op.create_index(
        op.f("ix_learning_item_next_review_due"), "learning_item", ["next_review_due"], unique=False
    )
    op.create_index(
        op.f("ix_learning_item_source_approval_id"),
        "learning_item",
        ["source_approval_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_item_source_note_id"), "learning_item", ["source_note_id"], unique=False
    )
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_type", sa.Enum("BOOK", "OTHER", name="sourcetype"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_title"), "source", ["title"], unique=False)
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tag_name"), "tag", ["name"], unique=True)
    op.create_table(
        "weekly_report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("week_end", sa.Date(), nullable=False),
        sa.Column("items_studied_count", sa.Integer(), nullable=False),
        sa.Column("quiz_summary_json", sa.JSON(), nullable=True),
        sa.Column("mini_writing_summary_json", sa.JSON(), nullable=True),
        sa.Column("weekly_writing_evaluation_id", sa.Integer(), nullable=True),
        sa.Column("mastery_snapshot_json", sa.JSON(), nullable=True),
        sa.Column("narrative_report", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["weekly_writing_evaluation_id"],
            ["writing_evaluation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_weekly_report_week_end"), "weekly_report", ["week_end"], unique=False)
    op.create_index(
        op.f("ix_weekly_report_week_start"), "weekly_report", ["week_start"], unique=True
    )
    op.create_index(
        op.f("ix_weekly_report_weekly_writing_evaluation_id"),
        "weekly_report",
        ["weekly_writing_evaluation_id"],
        unique=False,
    )
    op.create_table(
        "writing_evaluation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("grammar_score", sa.Float(), nullable=True),
        sa.Column("naturalness_score", sa.Float(), nullable=True),
        sa.Column("vocabulary_score", sa.Float(), nullable=True),
        sa.Column("coherence_score", sa.Float(), nullable=True),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("feedback_json", sa.JSON(), nullable=True),
        sa.Column("suggested_items_json", sa.JSON(), nullable=True),
        sa.Column("evaluator_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("evaluator_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("prompt_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("rubric_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["writing_submission.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_writing_evaluation_submission_id"),
        "writing_evaluation",
        ["submission_id"],
        unique=False,
    )
    op.create_table(
        "writing_prompt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "prompt_type", sa.Enum("MINI", "WEEKLY", name="writingprompttype"), nullable=False
        ),
        sa.Column("topic", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=False),
        sa.Column("week_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["week_id"],
            ["weekly_report.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_writing_prompt_prompt_type"), "writing_prompt", ["prompt_type"], unique=False
    )
    op.create_index(op.f("ix_writing_prompt_topic"), "writing_prompt", ["topic"], unique=False)
    op.create_index(op.f("ix_writing_prompt_week_id"), "writing_prompt", ["week_id"], unique=False)
    op.create_table(
        "writing_submission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prompt_id", sa.Integer(), nullable=False),
        sa.Column(
            "submission_type",
            sa.Enum("MINI", "WEEKLY", name="writingsubmissiontype"),
            nullable=False,
        ),
        sa.Column("submitted_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["writing_prompt.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_writing_submission_prompt_id"), "writing_submission", ["prompt_id"], unique=False
    )
    op.create_index(
        op.f("ix_writing_submission_submission_type"),
        "writing_submission",
        ["submission_type"],
        unique=False,
    )
    op.create_table(
        "learning_item_tag",
        sa.Column("learning_item_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("learning_item_id", "tag_id"),
    )
    op.create_table(
        "lesson",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lesson_source_id"), "lesson", ["source_id"], unique=False)
    op.create_index(op.f("ix_lesson_title"), "lesson", ["title"], unique=False)
    op.create_table(
        "performance_error",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("learning_item_id", sa.Integer(), nullable=True),
        sa.Column("wrong_form", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("correct_form", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("explanation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum("QUIZ", "WRITING_MINI", "WRITING_WEEKLY", name="performanceerrorsource"),
            nullable=False,
        ),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_performance_error_created_at"), "performance_error", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_performance_error_learning_item_id"),
        "performance_error",
        ["learning_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_performance_error_source_id"), "performance_error", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_performance_error_source_type"), "performance_error", ["source_type"], unique=False
    )
    op.create_table(
        "quiz_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "quiz_scope", sa.Enum("AD_HOC", "WEEKLY_REVIEW", name="quizscope"), nullable=False
        ),
        sa.Column(
            "quiz_mode",
            sa.Enum(
                "RECALL",
                "FILL_BLANK",
                "MULTIPLE_CHOICE",
                "ERROR_CORRECTION",
                "REWRITE_NATURALLY",
                "CONVERSATION",
                "MINI_ESSAY",
                "RANDOM",
                name="quizmode",
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("week_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["week_id"],
            ["weekly_report.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quiz_session_quiz_mode"), "quiz_session", ["quiz_mode"], unique=False)
    op.create_index(
        op.f("ix_quiz_session_quiz_scope"), "quiz_session", ["quiz_scope"], unique=False
    )
    op.create_index(op.f("ix_quiz_session_week_id"), "quiz_session", ["week_id"], unique=False)
    op.create_table(
        "note",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vault_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW", "PARSING", "PENDING_APPROVAL", "PROCESSED", "PARSE_FAILED", name="notestatus"
            ),
            nullable=False,
        ),
        sa.Column("changed_since_processed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lesson.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_note_lesson_id"), "note", ["lesson_id"], unique=False)
    op.create_index(op.f("ix_note_status"), "note", ["status"], unique=False)
    op.create_index(op.f("ix_note_vault_path"), "note", ["vault_path"], unique=True)
    op.create_table(
        "quiz_question",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quiz_session_id", sa.Integer(), nullable=False),
        sa.Column("learning_item_id", sa.Integer(), nullable=True),
        sa.Column(
            "question_type",
            sa.Enum(
                "RECALL",
                "FILL_BLANK",
                "MULTIPLE_CHOICE",
                "ERROR_CORRECTION",
                "REWRITE_NATURALLY",
                "CONVERSATION",
                "MINI_ESSAY",
                "RANDOM",
                name="quizmode",
            ),
            nullable=False,
        ),
        sa.Column("prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("correct_answer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_answer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("graded_by", sa.Enum("DETERMINISTIC", "LLM", name="gradedby"), nullable=True),
        sa.Column("evaluator_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("evaluator_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("prompt_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("rubric_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quiz_session_id"],
            ["quiz_session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quiz_question_learning_item_id"),
        "quiz_question",
        ["learning_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quiz_question_question_type"), "quiz_question", ["question_type"], unique=False
    )
    op.create_index(
        op.f("ix_quiz_question_quiz_session_id"), "quiz_question", ["quiz_session_id"], unique=False
    )
    op.create_table(
        "learning_correction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wrong_form", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("correct_form", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("explanation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("example_sentence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_note_id", sa.Integer(), nullable=True),
        sa.Column("source_writing_evaluation_id", sa.Integer(), nullable=True),
        sa.Column("source_approval_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_approval_id"],
            ["approval_queue.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_note_id"],
            ["note.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_writing_evaluation_id"],
            ["writing_evaluation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_correction_created_at"),
        "learning_correction",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_correction_source_approval_id"),
        "learning_correction",
        ["source_approval_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_correction_source_note_id"),
        "learning_correction",
        ["source_note_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_correction_source_writing_evaluation_id"),
        "learning_correction",
        ["source_writing_evaluation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_learning_correction_source_writing_evaluation_id"),
        table_name="learning_correction",
    )
    op.drop_index(op.f("ix_learning_correction_source_note_id"), table_name="learning_correction")
    op.drop_index(
        op.f("ix_learning_correction_source_approval_id"), table_name="learning_correction"
    )
    op.drop_index(op.f("ix_learning_correction_created_at"), table_name="learning_correction")
    op.drop_table("learning_correction")
    op.drop_index(op.f("ix_quiz_question_quiz_session_id"), table_name="quiz_question")
    op.drop_index(op.f("ix_quiz_question_question_type"), table_name="quiz_question")
    op.drop_index(op.f("ix_quiz_question_learning_item_id"), table_name="quiz_question")
    op.drop_table("quiz_question")
    op.drop_index(op.f("ix_note_vault_path"), table_name="note")
    op.drop_index(op.f("ix_note_status"), table_name="note")
    op.drop_index(op.f("ix_note_lesson_id"), table_name="note")
    op.drop_table("note")
    op.drop_index(op.f("ix_quiz_session_week_id"), table_name="quiz_session")
    op.drop_index(op.f("ix_quiz_session_quiz_scope"), table_name="quiz_session")
    op.drop_index(op.f("ix_quiz_session_quiz_mode"), table_name="quiz_session")
    op.drop_table("quiz_session")
    op.drop_index(op.f("ix_performance_error_source_type"), table_name="performance_error")
    op.drop_index(op.f("ix_performance_error_source_id"), table_name="performance_error")
    op.drop_index(op.f("ix_performance_error_learning_item_id"), table_name="performance_error")
    op.drop_index(op.f("ix_performance_error_created_at"), table_name="performance_error")
    op.drop_table("performance_error")
    op.drop_index(op.f("ix_lesson_title"), table_name="lesson")
    op.drop_index(op.f("ix_lesson_source_id"), table_name="lesson")
    op.drop_table("lesson")
    op.drop_table("learning_item_tag")
    op.drop_index(op.f("ix_writing_submission_submission_type"), table_name="writing_submission")
    op.drop_index(op.f("ix_writing_submission_prompt_id"), table_name="writing_submission")
    op.drop_table("writing_submission")
    op.drop_index(op.f("ix_writing_prompt_week_id"), table_name="writing_prompt")
    op.drop_index(op.f("ix_writing_prompt_topic"), table_name="writing_prompt")
    op.drop_index(op.f("ix_writing_prompt_prompt_type"), table_name="writing_prompt")
    op.drop_table("writing_prompt")
    op.drop_index(op.f("ix_writing_evaluation_submission_id"), table_name="writing_evaluation")
    op.drop_table("writing_evaluation")
    op.drop_index(op.f("ix_weekly_report_weekly_writing_evaluation_id"), table_name="weekly_report")
    op.drop_index(op.f("ix_weekly_report_week_start"), table_name="weekly_report")
    op.drop_index(op.f("ix_weekly_report_week_end"), table_name="weekly_report")
    op.drop_table("weekly_report")
    op.drop_index(op.f("ix_tag_name"), table_name="tag")
    op.drop_table("tag")
    op.drop_index(op.f("ix_source_title"), table_name="source")
    op.drop_table("source")
    op.drop_index(op.f("ix_learning_item_source_note_id"), table_name="learning_item")
    op.drop_index(op.f("ix_learning_item_source_approval_id"), table_name="learning_item")
    op.drop_index(op.f("ix_learning_item_next_review_due"), table_name="learning_item")
    op.drop_index(op.f("ix_learning_item_item_type"), table_name="learning_item")
    op.drop_index(op.f("ix_learning_item_created_at"), table_name="learning_item")
    op.drop_table("learning_item")
    op.drop_table("config")
    op.drop_index(op.f("ix_audit_log_timestamp"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_event_type"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_approval_queue_status"), table_name="approval_queue")
    op.drop_index(op.f("ix_approval_queue_source_type"), table_name="approval_queue")
    op.drop_index(op.f("ix_approval_queue_source_id"), table_name="approval_queue")
    op.drop_index(op.f("ix_approval_queue_possible_duplicate_of"), table_name="approval_queue")
    op.drop_index(op.f("ix_approval_queue_item_type"), table_name="approval_queue")
    op.drop_table("approval_queue")
    # ### end Alembic commands ###
